# Automate android build on tag push
name: Build Android

# Push whenever new tag assigned (ideally app version number)
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Install @angular/cli
        run: npm i -D -E @angular/cli
      - name: Setup Ionic Workspace
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8
      - name: Build debug apk
        run: ionic cordova build android
      - name: Upload app
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
