name: Create App Release

# Push whenever new tag assigned
# on:
#   push:
#     tags:
#       - "*"
on:
  push:
    branches:    
      - actions
jobs:
  build:
    name: Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Install @angular/cli
        run: npm i -D -E @angular/cli
      - name: Setup Ionic Workspace
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8
      - name: Build debug apk
        run: ionic cordova build android
      - name: Create release and upload apk
        uses: ncipollo/release-action@v1
          with:
            artifacts: "platforms/android/app/build/outputs/apk/debug/*.apk"
            body: "Automated release"
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
            # Todo - remove explicit tag once working to use push tags
            tag: "1.1.1"
